sequenceDiagram
	participant B as Backend
	box System under test (Cursor)
		participant A as AutoGUI
	  participant C as Cursor IDE
  end

	B-->>A: Request for sub-sequent edit suggestion
	A-->>C: Apply the last edit & current project status
	C-->>C: Sync project status
	C-->>C: Generate sub-sequent edit sugggestions
	C-->>A: Extract sub-sequent edit suggestions
	A-->>B: Return sub-sequent edit suggestions