sequenceDiagram
	participant B as Backend
	box System under test (CoEdPilot)
		participant D as Discriminator
	  participant L as Locator
	  participant G as Generator
  end

	B-->>D: Request for sub-sequent edit suggestion
	D-->>D: Filter potential files
	D-->>L: Send prior edits & potential files
	L-->>L: Find sub-sequent edit locations
	L-->>G: Send prior edits & sub-sequent edit locations & edit labels
	G-->>G: Generate edit solutions
	G-->>B: Return edit locations and solutions